### ISSUE TITLE
What is the meaning of ">>>"

### ISSUE THREAD

**Issue by HereChen** [Akryum/vue-resize#91]
What is the meaning of ">>>"?

```css
.resize-observer >>> object {
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  overflow: hidden;
  pointer-events: none;
  z-index: -1;
}
```

[code here](https://github.com/Akryum/vue-resize/blob/8f9d80035920d7ec6719816ff9b3ee73c86430af/src/components/ResizeObserver.vue#L95), and also [fix: style object with CSS, closes #4](https://github.com/Akryum/vue-resize/commit/1738a09b307f9be7700414e780630e81caae8f0d)
